# Generated by Django 5.0.7 on 2024-09-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_date_joined_customuser_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
