# Generated by Django 5.0.7 on 2024-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_managers_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_permis',
            field=models.DateField(default='01-01-2001'),
        ),
    ]
