# Generated by Django 5.0.7 on 2024-09-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_date_permis'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='npermis',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
