# Generated by Django 5.0.7 on 2024-10-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_npermis'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='Conducteur', max_length=255),
        ),
    ]
