# Generated by Django 5.1 on 2024-08-17 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Constat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('temoin', models.TextField(blank=True, null=True)),
                ('degat_a', models.TextField(blank=True, null=True)),
                ('degat_b', models.TextField(blank=True, null=True)),
                ('blessure_a', models.TextField(blank=True, null=True)),
                ('blessure_b', models.TextField(blank=True, null=True)),
                ('circonstances_a', models.TextField(blank=True, null=True)),
                ('circonstances_b', models.TextField(blank=True, null=True)),
                ('observation_a', models.TextField(blank=True, null=True)),
                ('observation_b', models.TextField(blank=True, null=True)),
                ('signature_a', models.CharField(max_length=255)),
                ('signature_b', models.CharField(max_length=255)),
                ('sens_a', models.TextField()),
                ('sens_b', models.TextField()),
                ('croquis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('date_naissance', models.DateField()),
                ('cin', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('date_permis', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssuranceContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_assurance', models.CharField(max_length=255)),
                ('police', models.CharField(max_length=255)),
                ('agence', models.CharField(max_length=255)),
                ('date_debut_attestation', models.DateField()),
                ('date_fin_attestation', models.DateField()),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='insurance.assure')),
            ],
        ),
        migrations.CreateModel(
            name='DegatApparent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degat', models.TextField()),
                ('images_accident', models.ImageField(upload_to='accident_images/')),
                ('videos_accident', models.FileField(blank=True, null=True, upload_to='accident_videos/')),
                ('constat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degats', to='insurance.constat')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='insurance.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('date_fabrication', models.DateField()),
                ('kilometrage', models.IntegerField()),
                ('vidange', models.BooleanField(default=False)),
                ('km_vidange', models.IntegerField()),
                ('assure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='insurance.assure')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entretien', models.CharField(max_length=255)),
                ('kilometrage', models.IntegerField()),
                ('date', models.DateField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='insurance.vehicle')),
            ],
        ),
    ]
