# Generated by Django 5.0.7 on 2024-09-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=20)),
                ('nom_assurance', models.CharField(default='', max_length=255)),
                ('police', models.CharField(default='', max_length=255)),
                ('agence', models.CharField(default='', max_length=255)),
                ('date_debut_attestation', models.DateField(default='01-01-2001')),
                ('date_fin_attestation', models.DateField(default='01-01-2001')),
            ],
        ),
    ]
