# Generated by Django 5.0.7 on 2024-08-24 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constat',
            name='vehicleA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constat_vehiclesA', to='insurance.user'),
        ),
        migrations.AddField(
            model_name='constat',
            name='vehicleB',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constat_vehiclesB', to='insurance.user'),
        ),
    ]
