# Generated by Django 5.0.7 on 2024-09-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_constat_vehiclea_constat_vehicleb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constat',
            name='blessure_a',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='blessure_b',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='circonstances_a',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='circonstances_b',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='croquis',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='degat_a',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='degat_b',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='observation_a',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='observation_b',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='sens_a',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='sens_b',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='signature_a',
        ),
        migrations.RemoveField(
            model_name='constat',
            name='signature_b',
        ),
        migrations.AlterField(
            model_name='constat',
            name='vehicleA',
            field=models.FileField(blank=True, null=True, upload_to='constat_vehicleA/'),
        ),
        migrations.AlterField(
            model_name='constat',
            name='vehicleB',
            field=models.FileField(blank=True, null=True, upload_to='constat_vehicleB/'),
        ),
    ]
