# Generated by Django 5.0.7 on 2024-09-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_remove_constat_blessure_a_remove_constat_blessure_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constat',
            name='croquis',
            field=models.FileField(blank=True, null=True, upload_to='constat_croquis/'),
        ),
    ]
