# Generated by Django 5.0.7 on 2024-09-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_constat_croquis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assurancecontrat',
            name='assure',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='kilometrage',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='km_vidange',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vidange',
        ),
        migrations.AddField(
            model_name='assure',
            name='contrat',
            field=models.FileField(blank=True, null=True, upload_to='contrats/'),
        ),
    ]
