# Generated by Django 5.0.7 on 2024-09-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_alter_assure_contrat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assure',
            name='contrat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assures', to='insurance.assurancecontrat'),
        ),
    ]
