# Generated by Django 5.0.7 on 2024-09-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('date_fabrication', models.DateField()),
                ('assure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance.assure')),
            ],
        ),
    ]
