# Generated by Django 5.0.7 on 2024-09-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_vehicle_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
