# Generated by Django 5.0.7 on 2024-09-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lieu', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('codeA', models.CharField(max_length=255)),
                ('codeB', models.CharField(max_length=255)),
                ('vehicleA', models.FileField(blank=True, null=True, upload_to='constat_vehicleA/')),
                ('vehicleB', models.FileField(blank=True, null=True, upload_to='constat_vehicleB/')),
            ],
        ),
    ]
