# Generated by Django 5.0.7 on 2024-09-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constat',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constat',
            name='codeA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constat',
            name='codeB',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='constat',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='constat',
            name='lieu',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
