# Generated by Django 5.0.7 on 2024-09-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Constat', '0002_alter_constat_code_alter_constat_codea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constat',
            name='code',
        ),
    ]
