# Generated by Django 5.0.7 on 2024-09-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constat', '0003_remove_constat_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='constat',
            name='cinA',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constat',
            name='cinB',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
