# Generated by Django 5.0.7 on 2024-10-06 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Constat', '0004_constat_cina_constat_cinb'),
    ]

    operations = [
        migrations.AddField(
            model_name='constat',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
